---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt
script:
  - pre-commit run --all-files
  - pytest --runslow
after_success:
  - coveralls
deploy:
  - provider: pypi
    user: felddy
    password:
      secure: "FjuPaZG2rE1UFOuX3DBIsGMYrVwBxjxMn/vQAU+826dYJkerHjAalwd\
      4i7oVHedqBIb9Mukvy6oG24COnCXncEs1bydPxg89bGC/ExRbch6+xDS44Z9KVVf\
      dcJpKHW7RWMfAGlnIVx+/IlsV4DoEdDvpeqr2ZDZkHA1FcbV3aKdhQfQUOw8GfeC\
      ShsAmlt4Kr3D3FzGW3+fARHzMXfoWJWr34L0Cp6mfH1wbBbCBAAGUAybQXVjIknz\
      xHXzS8CHEQwcv58QyD3SwPZGZkGlDeWypfztrRf10VVqljZgMxghgxSOKwF9vmdj\
      5+4B0FYidDcYMrWkW5Q2msk/vOFOLLHs5p8Cci4d1Qe79arsNBWL8KsjXRSTymxa\
      L8xEtfhqP5bfRcP/chRSnBe7pW/ej8Se9GZWsJQfuJYhzmkZBtEQfZcXGQg11x4Q\
      915UOG9HKOh6RKs4/JQfJOLdSCISxgnADi8qnhEiZSEf9JnUpEG0fJeoBk0TcTGh\
      Vd6wiGUX11r2lKgEPpwhXKdVG8ns9/P8VDhLJr36bn0+ce+4CmJAt5tUer8ruocg\
      qICUiJ84YSK3rVfQkpYN/AYjuFxjtlrChZKHRjVxEjh1UdA2pyuLwP/p9OXwgkQe\
      RtGzHsIkj0jfA++B8zP/YYIIKtCuCN8I7a7tnBI9ebZF8WcTesw0="
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: '3.7'
